services:
  backend:
    build:
      dockerfile: ./Dockerfile
    image: space-game-backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
